package edu.moravian.csci215.finalproject395_truthfulcheckers.theme

data class AppStrings(
    val appName: String,
    val playGame: String,
    val howToPlay: String,
    val settings: String,
    val selectMode: String,
    val vsAi: String,
    val localMulti: String,
    val back: String,
    val gameSetup: String,
    val localMatchSetup: String, // NEW
    val p1Name: String,
    val p2Name: String,
    val player1Name: String, // NEW
    val player2Name: String, // NEW
    val aiBotOptional: String, // NEW
    val aiBotDefault: String, // NEW
    val aiDifficulty: String,
    val startBattle: String,
    val yourTurn: String,
    val forfeit: String,
    val time: String,
    val triviaGate: String,
    val triviaCategory: String, // NEW
    val loading: String, // NEW
    val easy: String, // NEW
    val medium: String, // NEW
    val hard: String, // NEW
    val trueText: String,
    val falseText: String,
    val gameOver: String,
    val playAgain: String,
    val backHome: String,
    val wins: String,
    val tie: String,
    val language: String,
    val theme: String,
    val boardStyle: String,
    val turnTimer: String,
    val soundEffects: String,
    val soundEffectsShort: String,
    val backgroundMusic: String,
    val backgroundMusicShort: String,
    val flippingCoin: String,
    val winsFlip: String,
    val goalTitle: String,
    val goalDesc: String,
    val movingTitle: String,
    val movingDesc: String,
    val triviaTitle: String,
    val triviaDesc: String,
    val emotionsTitle: String,
    val emotionsDesc: String,
    val customTitle: String,
    val customDesc: String,
    val appearance: String,
    val gameSettings: String,
    val audio: String,
    val onlineMultiplayer: String,
    val createRoom: String,
    val joinRoom: String,
    val createGame: String,
    val joinGame: String,
    val yourName: String,
    val roomCode: String,
    val startRoom: String,
    val room: String,
    val you: String,
    val spectating: String,
    val category: String,
    val difficulty: String,
    val opponentsTurn: String,
    val waiting: String,
    val waitingForOpponent: String,
    val shareCode: String,
    val roomClosed: String,
    val roomClosedMessage: String,
    val errorNoQuestion: String,
)

val EnglishStrings =
    AppStrings(
        appName = "Truthful Checkers",
        playGame = "Play Game",
        howToPlay = "How to Play",
        settings = "Settings",
        selectMode = "Select Mode",
        vsAi = "Single Player (vs AI)",
        localMulti = "Local Multiplayer",
        back = "Back",
        gameSetup = "Game Setup",
        localMatchSetup = "Local Match Setup",
        p1Name = "Player 1 Name",
        p2Name = "Player 2 Name",
        player1Name = "Player 1 Name",
        player2Name = "Player 2 Name",
        aiBotOptional = "AI Bot Name (Optional)",
        aiBotDefault = "AI Bot",
        aiDifficulty = "AI Difficulty",
        startBattle = "Start Battle",
        yourTurn = "YOUR TURN",
        forfeit = "FORFEIT",
        time = "Time",
        triviaGate = "TRIVIA GATE",
        triviaCategory = "Trivia Category",
        loading = "Loading...",
        easy = "Easy",
        medium = "Medium",
        hard = "Hard",
        trueText = "TRUE",
        falseText = "FALSE",
        gameOver = "Game Over!",
        playAgain = "Play Again",
        backHome = "Back to Home",
        wins = "Wins!",
        tie = "It's a Tie! 🤝",
        language = "Language:",
        theme = "Theme:",
        boardStyle = "Board Style:",
        turnTimer = "Turn Countdown Timer:",
        soundEffects = "Sound Effects",
        soundEffectsShort = "SFX",
        backgroundMusic = "Background Music",
        backgroundMusicShort = "Music",
        flippingCoin = "Flipping Coin...",
        winsFlip = "Wins Flip!",
        goalTitle = "1. Goal",
        goalDesc = "Capture all of your opponent's pieces or block them so they can't move.",
        movingTitle = "2. Moving",
        movingDesc = "Pieces move diagonally on dark squares. Standard pieces move forward; Kings can move forward and backward.",
        triviaTitle = "3. Trivia Gate",
        triviaDesc = "Before every move, you must answer a True/False question. Correct answers allow the move. Incorrect answers skip your turn!",
        emotionsTitle = "4. Emotions",
        emotionsDesc = "Watch your pieces! They get HAPPY 😄 when safe, MAD 😡 when they can jump, SCARED 😨 when they might be captured, and CONFUSED 😕 if you get a question wrong.",
        customTitle = "5. Customizing Trivia",
        customDesc = "Go to the Setup screen before starting a game to change categories and difficulty for a fresh challenge.",
        appearance = "Appearance",
        gameSettings = "Game Settings",
        audio = "Audio",
        onlineMultiplayer = "Online Multiplayer",
        createRoom = "Create Room",
        joinRoom = "Join Room",
        createGame = "Create Game",
        joinGame = "Join Game",
        yourName = "Your Name",
        roomCode = "6-Digit Room Code",
        startRoom = "Start Room",
        room = "Room",
        you = "You",
        spectating = "Spectating",
        category = "Category",
        difficulty = "Difficulty",
        opponentsTurn = "Opponent's Turn",
        waiting = "Waiting...",
        waitingForOpponent = "Waiting for opponent to join...",
        shareCode = "Share code",
        roomClosed = "Room Closed",
        roomClosedMessage = "The room has been closed.",
        errorNoQuestion = "No Question Available",
    )

val SpanishStrings =
    AppStrings(
        appName = "Damas Veraces",
        playGame = "Jugar",
        howToPlay = "Cómo Jugar",
        settings = "Ajustes",
        selectMode = "Seleccionar Modo",
        vsAi = "Un Jugador (vs IA)",
        localMulti = "Multijugador Local",
        back = "Volver",
        gameSetup = "Configuración",
        localMatchSetup = "Partida Local",
        p1Name = "Nombre Jugador 1",
        p2Name = "Nombre Jugador 2",
        player1Name = "Nombre Jugador 1",
        player2Name = "Nombre Jugador 2",
        aiBotOptional = "Nombre de IA (Opcional)",
        aiBotDefault = "Bot IA",
        aiDifficulty = "Dificultad IA",
        startBattle = "Empezar Batalla",
        yourTurn = "TU TURNO",
        forfeit = "RENDIRSE",
        time = "Tiempo",
        triviaGate = "PUERTA DE TRIVIA",
        triviaCategory = "Categoría de Trivia",
        loading = "Cargando...",
        easy = "Fácil",
        medium = "Medio",
        hard = "Difícil",
        trueText = "VERDADERO",
        falseText = "FALSO",
        gameOver = "¡Juego Terminado!",
        playAgain = "Jugar de Nuevo",
        backHome = "Volver al Inicio",
        wins = "¡Gana!",
        tie = "¡Es un empate! 🤝",
        language = "Idioma:",
        theme = "Tema:",
        boardStyle = "Estilo de Tablero:",
        turnTimer = "Temporizador de Turno:",
        soundEffects = "Efectos de Sonido",
        soundEffectsShort = "EFX",
        backgroundMusic = "Música de Fondo",
        backgroundMusicShort = "Música",
        flippingCoin = "Lanzando moneda...",
        winsFlip = "¡Gana el sorteo!",
        goalTitle = "1. Objetivo",
        goalDesc = "Captura todas las piezas de tu oponente o bloquéalas para que no puedan moverse.",
        movingTitle = "2. Movimiento",
        movingDesc = "Las piezas se mueven diagonalmente en los cuadros oscuros. Las piezas estándar avanzan; los Reyes pueden avanzar y retroceder.",
        triviaTitle = "3. Puerta de Trivia",
        triviaDesc = "Antes de cada movimiento, debes responder una pregunta de Verdadero/Falso. Las respuestas correctas permiten el movimiento. ¡Las incorrectas saltan tu turno!",
        emotionsTitle = "4. Emociones",
        emotionsDesc = "¡Mira tus piezas! Se ponen FELICES 😄 cuando están a salvo, ENOJADAS 😡 cuando pueden saltar, ASUSTADAS 😨 cuando pueden ser capturadas, y CONFUNDIDAS 😕 si respondes mal.",
        customTitle = "5. Personalizar Trivia",
        customDesc = "Ve a la pantalla de Configuración antes de empezar para cambiar categorías y dificultad.",
        appearance = "Apariencia",
        gameSettings = "Ajustes de Juego",
        audio = "Audio",
        onlineMultiplayer = "Multijugador en Línea",
        createRoom = "Crear Sala",
        joinRoom = "Unirse a Sala",
        createGame = "Crear Juego",
        joinGame = "Unirse al Juego",
        yourName = "Tu Nombre",
        roomCode = "Código de Sala de 6 Dígitos",
        startRoom = "Iniciar Sala",
        room = "Sala",
        you = "Tú",
        spectating = "Espectador",
        category = "Categoría",
        difficulty = "Dificultad",
        opponentsTurn = "Turno del Oponente",
        waiting = "Esperando...",
        waitingForOpponent = "Esperando a que se una el oponente...",
        shareCode = "Comparte el código",
        roomClosed = "Sala Cerrada",
        roomClosedMessage = "La sala ha sido cerrada.",
        errorNoQuestion = "Pregunta no disponible",
    )

val FrenchStrings =
    AppStrings(
        appName = "Dames Véridiques",
        playGame = "Jouer",
        howToPlay = "Comment Jouer",
        settings = "Paramètres",
        selectMode = "Mode de Jeu",
        vsAi = "Solo (vs IA)",
        localMulti = "Multijugador Local",
        back = "Retour",
        gameSetup = "Configuration",
        localMatchSetup = "Match Local",
        p1Name = "Nom Joueur 1",
        p2Name = "Nom Joueur 2",
        player1Name = "Nom Joueur 1",
        player2Name = "Nom Joueur 2",
        aiBotOptional = "Nom de l'IA (Optionnel)",
        aiBotDefault = "Bot IA",
        aiDifficulty = "Difficulté IA",
        startBattle = "Commencer",
        yourTurn = "VOTRE TOUR",
        forfeit = "ABANDONNER",
        time = "Temps",
        triviaGate = "PORTE DE TRIVIA",
        triviaCategory = "Catégorie",
        loading = "Chargement...",
        easy = "Facile",
        medium = "Moyen",
        hard = "Difficile",
        trueText = "VRAI",
        falseText = "FAUX",
        gameOver = "Fin de partie !",
        playAgain = "Rejouer",
        backHome = "Retour à l'accueil",
        wins = "Gagne !",
        tie = "Match nul ! 🤝",
        language = "Langue :",
        theme = "Thème :",
        boardStyle = "Style de Plateau :",
        turnTimer = "Chronomètre de Tour :",
        soundEffects = "Effets Sonores",
        soundEffectsShort = "Effets",
        backgroundMusic = "Musique de Fond",
        backgroundMusicShort = "Musique",
        flippingCoin = "Lancer de pièce...",
        winsFlip = "Gagne le tirage !",
        goalTitle = "1. Objectif",
        goalDesc = "Capturez toutes les pièces de votre adversaire ou bloquez-les pour qu'elles ne puissent plus bouger.",
        movingTitle = "2. Déplacement",
        movingDesc = "Les pièces se déplacent en diagonale sur les cases sombres. Les pièces normales avancent ; les Rois peuvent avancer et reculer.",
        triviaTitle = "3. Porte de Trivia",
        triviaDesc = "Avant chaque mouvement, vous devez répondre à une question Vrai/Faux. Les bonnes réponses permettent le mouvement. Les mauvaises sautent votre tour !",
        emotionsTitle = "4. Émotions",
        emotionsDesc = "Regardez vos pièces ! Elles sont CONTENTES 😄 en sécurité, EN COLÈRE 😡 quand elles peuvent sauter, EFFRAYÉES 😨 quand elles risquent d'être capturées, et CONFUSES 😕 en cas de mauvaise réponse.",
        customTitle = "5. Personnalisation",
        customDesc = "Allez dans la configuration avant de commencer pour changer les catégories et la difficulté.",
        appearance = "Apparence",
        gameSettings = "Paramètres de Jeu",
        audio = "Audio",
        onlineMultiplayer = "Multijoueur en Ligne",
        createRoom = "Créer une Salle",
        joinRoom = "Rejoindre une Salle",
        createGame = "Créer une Partie",
        joinGame = "Rejoindre la Partie",
        yourName = "Votre Nom",
        roomCode = "Code de Salle à 6 Chiffres",
        startRoom = "Démarrer la Salle",
        room = "Salle",
        you = "Vous",
        spectating = "Spectateur",
        category = "Catégorie",
        difficulty = "Difficulté",
        opponentsTurn = "Tour de l'Adversaire",
        waiting = "En attente...",
        waitingForOpponent = "En attente de l'adversaire...",
        shareCode = "Partager le code",
        roomClosed = "Salle Fermée",
        roomClosedMessage = "La salle a été fermée.",
        errorNoQuestion = "Aucune question disponible",
    )

fun getStrings(language: String): AppStrings =
    when (language) {
        "Spanish" -> SpanishStrings
        "French" -> FrenchStrings
        else -> EnglishStrings
    }
